version: '2'
services:
  shopio:
    build:
      context: ../
      dockerfile: ./sio-build-ear/Dockerfile
    environment:
      JAVA_OPTS: -server -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256M -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=8787
    depends_on:
      - dbpostgresql
    ports:
      - 8080:8080
      - 9960:9990
      - 8787:8787
  dbpostgresql:
    image: postgres:10.5
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=fx
      - POSTGRES_DB=shopio
    volumes:
      - database-data:/var/lib/postgresql/data/    
    ports:
      - 5432:5432
volumes:
  database-data: {}